// flow-typed signature: 2236218b933c4968c72c9eadf0c5187e
// flow-typed version: <<STUB>>/reset-css_v^2.2.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reset-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'reset-css' {
  declare module.exports: any;
}
