/* @flow */

export const SET_SKILLS = 'SET_SKILLS'
export const SET_SKILL_VALUE = 'SET_SKILL_VALUE'

export const SET_COMPANY_VALUES = 'SET_COMPANY_VALUES'
export const SET_COMPANY_VALUE_VALUE = 'SET_COMPANY_VALUE_VALUE'

export const SET_USER = 'SET_USER'
